name: Update README
on:
  pull_request:
    types: [opened, synchronized, reopened]
  push:
    branches:
      - main
  fork:
  watch:
  schedule:
    - cron: "* * * * *"
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "New activity updated"
          MAX_LINES: 5
          COMMIT_NAME: GitHub Activity Readme
